version: '3'
services:
  web:
    build: .
    command: pipenv run flask run --host=0.0.0.0
    environment:
      FLASK_APP: web/server.py
      FLASK_ENV: development
    ports:
      - 5000:5000
    volumes:
      - .:/app
